In [28]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b=np.array([[21,22,23,24],[25,26,27,28],[29,30,31,32],[33,34,35,36]])

**DIMENSIONS**

In [29]:
print("Dimensions of A: ",a.ndim)
print("Size of A: ",a.size)
print("Shape of A: ",a.shape)
a

Dimensions of A:  2
Size of A:  16
Shape of A:  (4, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**ADDITION**

In [30]:
print("Addition of A & B ")
print(a+b)

Addition of A & B 
[[22 24 26 28]
 [30 32 34 36]
 [38 40 42 44]
 [46 48 50 52]]


**TRANSPOSE**

In [31]:
print("Transpose of A: \n",np.transpose(a))
print("Transpose of B: \n",np.transpose(b))

Transpose of A: 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Transpose of B: 
 [[21 25 29 33]
 [22 26 30 34]
 [23 27 31 35]
 [24 28 32 36]]


**DOT PRODUCT**

In [32]:
print(a.dot(b))

[[ 290  300  310  320]
 [ 722  748  774  800]
 [1154 1196 1238 1280]
 [1586 1644 1702 1760]]


**ELEMENT WISE MULTIPLICATION**

In [33]:
print(a*b)

[[ 21  44  69  96]
 [125 156 189 224]
 [261 300 341 384]
 [429 476 525 576]]


**ACCESING ELEMENTS**

In [39]:
print("Element",a[3][2])
print("Row",a[2])
print("Column",a[:,2])  

Element 15
Row [ 9 10 11 12]
Column [ 3  7 11 15]


**SLICE & REVERSE**

In [47]:
print("Slice: \n",a[slice(0,3,2)])
print("Reverse: \n",np.flipud(a))

Slice: 
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Reverse: 
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


**IMPORTING CSV DATA INTO NUMPY**

In [55]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/devilsboy/DL-Lab-1/master/california_housing_train.csv")
lat = data["latitude"]
print(data)

       longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]


**CREATING A MATRIX ON LATITUDE DATA**

In [56]:
np.matrix(lat)

matrix([[34.19, 34.4 , 33.69, ..., 41.84, 41.8 , 40.54]])

**CREATING A ARRAY ON LATITUDE DATA**

In [57]:
np.array(lat)

array([34.19, 34.4 , 33.69, ..., 41.84, 41.8 , 40.54])